import type { YiBaoPartKeyInfo } from "../interface";

/** @description 圆环 */
export const ANNULUS_COLOR = [
  { id: "dd09", color: "var(--white)" },
  { id: "ou51", color: "#e74c3c" },
  { id: "wr44", color: "#e67e22" },
  { id: "i4k2", color: "#f1c40f" },
  { id: "yi92", color: "#2ecc71" },
  { id: "x4k2", color: "#12cbc4" },
  { id: "d6h3", color: "#0078bd" },
  { id: "dn92", color: "#be2edd" },
];
export const ANNULUS_IMG = [
  { id: "tp44", img: "annulus_apple_small" },
  { id: "hq05", img: "annulus_bamboo_small" },
  { id: "e2n3", img: "annulus_blaze_powder_small" },
  { id: "n9p2", img: "annulus_bone_small" },
  { id: "zo60", img: "annulus_bucket_lava_small" },
  { id: "vc25", img: "annulus_bucket_water_small" },
  { id: "qt21", img: "annulus_cake_small" },
  { id: "gz88", img: "annulus_carrot_small" },
  { id: "hs43", img: "annulus_chicken_cooked_small" },
  { id: "zl95", img: "annulus_clock_item_small" },
  { id: "w52z", img: "annulus_coal_small" },
  { id: "xt20", img: "annulus_compass_item_small" },
  { id: "uq54", img: "annulus_cookie_small" },
  { id: "la77", img: "annulus_diamond_small" },
  { id: "lr11", img: "annulus_diamond_pickaxe_small" },
  { id: "kk81", img: "annulus_diamond_axe_small" },
  { id: "e9k8", img: "annulus_diamond_shovel_small" },
  { id: "b4n8", img: "annulus_diamond_hoe_small" },
  { id: "og09", img: "annulus_diamond_sword_small" },
  { id: "jh83", img: "annulus_dragons_breath_small" },
  { id: "c3c7", img: "annulus_dye_powder_blue_small" },
  { id: "v4r8", img: "annulus_emerald_small" },
  { id: "li63", img: "annulus_ender_eye_small" },
  { id: "k1x0", img: "annulus_ender_pearl_small" },
  { id: "mb84", img: "annulus_experience_bottle_small" },
  { id: "ra82", img: "annulus_fireball_small" },
  { id: "t3g5", img: "annulus_fireworks_small" },
  { id: "cw30", img: "annulus_fish_clownfish_raw_small" },
  { id: "fg95", img: "annulus_fish_pufferfish_raw_small" },
  { id: "f7x7", img: "annulus_fish_salmon_raw_small" },
  { id: "k87g", img: "annulus_flower_dandelion_small" },
  { id: "bb70", img: "annulus_flower_rose_small" },
  { id: "tv90", img: "annulus_gold_ingot_small" },
  { id: "g9v9", img: "annulus_melon_small" },
  { id: "ml06", img: "annulus_nether_star_small" },
  { id: "jt50", img: "annulus_record_13_small" },
  { id: "a5w0", img: "annulus_record_blocks_small" },
  { id: "df69", img: "annulus_record_cat_small" },
  { id: "l9g3", img: "annulus_record_chirp_small" },
  { id: "w3a1", img: "annulus_record_far_small" },
  { id: "mo53", img: "annulus_record_mellohi_small" },
  { id: "ss35", img: "annulus_record_stal_small" },
  { id: "qd12", img: "annulus_record_strad_small" },
  { id: "iv15", img: "annulus_record_wait_small" },
  { id: "w9j7", img: "annulus_record_ward_small" },
  { id: "zp43", img: "annulus_redstone_dust_small" },
  { id: "su32", img: "annulus_slimeball_small" },
  { id: "g81a", img: "annulus_snowball_small" },
  { id: "mb22", img: "annulus_totem_small" },
  { id: "o6o3", img: "annulus_trident_small" },
];

/** @description 天线 */
export const ANTENNA_COLOR = [
  { id: "sa20", colors: ["var(--white-25)", "var(--black-50)"] },
  { id: "hq73", colors: ["rgba(231, 76, 60,0.25)", "#e74c3c"] },
  { id: "wh10", colors: ["rgba(230, 126, 34,0.25)", "#e67e22"] },
  { id: "qk29", colors: ["rgba(241, 196, 15,0.25)", "#f1c40f"] },
  { id: "x90w", colors: ["rgba(46, 204, 113,0.25)", "#2ecc71"] },
  { id: "wi00", colors: ["rgba(18, 203, 196,0.25)", "#12cbc4"] },
  { id: "v4j2", colors: ["rgba(52, 152, 219,0.25)", "#3498db"] },
  { id: "ev89", colors: ["rgba(190, 46, 221,0.25)", "#be2edd"] },
];
export const ANTENNA_IMG: Record<string, string>[] = [
  { id: "cx34", img: "side_dirt_small" },
  { id: "v58o", img: "side_cobblestone_small" },
  { id: "mq32", img: "side_netherrack_small" },
  { id: "wl36", img: "side_soul_sand_small" },
  { id: "ts02", img: "side_bedrock_small" },
  { id: "tc30", img: "side_log_oak_small" },
  { id: "ad16", img: "side_log_spruce_small" },
  { id: "xb12", img: "side_log_big_oak_small" },
  { id: "ec53", img: "side_log_birch_small" },
  { id: "jo73", img: "side_log_acacia_small" },
  { id: "h0j8", img: "side_log_jungle_small" },
  { id: "ec25", img: "side_jukebox_side_small" },
  { id: "sh59", img: "side_tnt_side_small" },
  { id: "v7v4", img: "side_iron_block_small" },
  { id: "qc57", img: "side_gold_block_small" },
  { id: "cu19", img: "side_lapis_block_small" },
  { id: "yf31", img: "side_emerald_block_small" },
  { id: "i04j", img: "side_redstone_block_small" },
  { id: "b40h", img: "side_slime_small" },
  { id: "c4l3", img: "side_hay_block_side_small" },
  { id: "vp00", img: "side_brick_small" },
  { id: "ic29", img: "side_melon_side_small" },
  { id: "yd41", img: "side_redstone_lamp_off_small" },
];

/** @description 腮红 */
export const BLUSH_COLOR = [
  { id: "nu37", color: "var(--white)" },
  { id: "b3r6", color: "#e74c3c" },
  { id: "w7x1", color: "#e67e22" },
  { id: "y5g2", color: "#f1c40f" },
  { id: "o00r", color: "#2ecc71" },
  { id: "e0d7", color: "#12cbc4" },
  { id: "nr35", color: "#0078bd" },
  { id: "os17", color: "#be2edd" },
];

/** @description 眼睛 */
export const EYE_COLOR = [
  { id: "wt02", colors: ["var(--black)", "var(--black-50)"] },
  { id: "tj88", colors: ["rgb(64, 21, 17)", "#e74c3c"] },
  { id: "lc39", colors: ["rgb(64, 35, 9)", "#e67e22"] },
  { id: "lq72", colors: ["rgb(64, 52, 4)", "#f1c40f"] },
  { id: "b61b", colors: ["rgb(14, 64, 35)", "#2ecc71"] },
  { id: "ar02", colors: ["rgb(6, 64, 62)", "#12cbc4"] },
  { id: "mc24", colors: ["rgb(0, 40, 64)", "#0078bd"] },
  { id: "bt67", colors: ["rgb(55, 13, 64)", "#be2edd"] },
];

/** @description 嘴巴 */
export const MOUTH_COLOR = [
  { id: "ay75", colors: ["var(--black)", "var(--white-50)"] },
  { id: "qs82", colors: ["rgb(64, 21, 17)", "#e74c3c"] },
  { id: "v46e", colors: ["rgb(64, 35, 9)", "#e67e22"] },
  { id: "t7y7", colors: ["rgb(64, 52, 4)", "#f1c40f"] },
  { id: "at06", colors: ["rgb(14, 64, 35)", "#2ecc71"] },
  { id: "rr93", colors: ["rgb(6, 64, 62)", "#12cbc4"] },
  { id: "uu32", colors: ["rgb(0, 40, 64)", "#0078bd"] },
  { id: "v2i1", colors: ["rgb(55, 13, 64)", "#be2edd"] },
];

/** @description 六面 */
export const SIDE_COLOR = [
  { id: "nw39", colors: ["var(--white-25)", "var(--black)"] },
  { id: "et63", colors: ["rgba(231, 76, 60,0.25)", "#e74c3c"] },
  { id: "ok10", colors: ["rgba(230, 126, 34,0.25)", "#e67e22"] },
  { id: "ed38", colors: ["rgba(241, 196, 15,0.25)", "#f1c40f"] },
  { id: "mk09", colors: ["rgba(46, 204, 113,0.25)", "#2ecc71"] },
  { id: "kz18", colors: ["rgba(18, 203, 196,0.25)", "#12cbc4"] },
  { id: "es19", colors: ["rgba(52, 152, 219,0.25)", "#3498db"] },
  { id: "z31m", colors: ["rgba(190, 46, 221,0.25)", "#be2edd"] },
];
export const SIDE_IMG: Record<string, string>[] = [
  {
    id: "y8d9",
    front: "side_dirt_small",
    back: "side_dirt_small",
    top: "side_dirt_small",
    bottom: "side_dirt_small",
    left: "side_dirt_small",
    right: "side_dirt_small",
    shadow: "1",
  },
  {
    id: "yw29",
    front: "side_grass_side_carried_small",
    back: "side_grass_side_carried_small",
    top: "side_grass_carried_small",
    bottom: "side_coarse_dirt_small",
    left: "side_grass_side_carried_small",
    right: "side_grass_side_carried_small",
    shadow: "1",
  },
  {
    id: "a7f8",
    front: "side_cobblestone_small",
    back: "side_cobblestone_small",
    top: "side_cobblestone_small",
    bottom: "side_cobblestone_small",
    left: "side_cobblestone_small",
    right: "side_cobblestone_small",
    shadow: "1",
  },
  {
    id: "uu92",
    front: "side_netherrack_small",
    back: "side_netherrack_small",
    top: "side_netherrack_small",
    bottom: "side_netherrack_small",
    left: "side_netherrack_small",
    right: "side_netherrack_small",
    shadow: "1",
  },
  {
    id: "w9p0",
    front: "side_soul_sand_small",
    back: "side_soul_sand_small",
    top: "side_soul_sand_small",
    bottom: "side_soul_sand_small",
    left: "side_soul_sand_small",
    right: "side_soul_sand_small",
    shadow: "1",
  },
  {
    id: "qk97",
    front: "side_bedrock_small",
    back: "side_bedrock_small",
    top: "side_bedrock_small",
    bottom: "side_bedrock_small",
    left: "side_bedrock_small",
    right: "side_bedrock_small",
    shadow: "1",
  },
  {
    id: "vp82",
    front: "side_log_oak_small",
    back: "side_log_oak_small",
    top: "side_log_oak_top_small",
    bottom: "side_log_oak_top_small",
    left: "side_log_oak_small",
    right: "side_log_oak_small",
    shadow: "1",
  },
  {
    id: "xs30",
    front: "side_log_spruce_small",
    back: "side_log_spruce_small",
    top: "side_log_spruce_top_small",
    bottom: "side_log_spruce_top_small",
    left: "side_log_spruce_small",
    right: "side_log_spruce_small",
    shadow: "1",
  },
  {
    id: "y93u",
    front: "side_log_big_oak_small",
    back: "side_log_big_oak_small",
    top: "side_log_big_oak_top_small",
    bottom: "side_log_big_oak_top_small",
    left: "side_log_big_oak_small",
    right: "side_log_big_oak_small",
    shadow: "1",
  },
  {
    id: "zg30",
    front: "side_log_birch_small",
    back: "side_log_birch_small",
    top: "side_log_birch_top_small",
    bottom: "side_log_birch_top_small",
    left: "side_log_birch_small",
    right: "side_log_birch_small",
    shadow: "1",
  },
  {
    id: "gk79",
    front: "side_log_acacia_small",
    back: "side_log_acacia_small",
    top: "side_log_acacia_top_small",
    bottom: "side_log_acacia_top_small",
    left: "side_log_acacia_small",
    right: "side_log_acacia_small",
    shadow: "1",
  },
  {
    id: "o4s2",
    front: "side_log_jungle_small",
    back: "side_log_jungle_small",
    top: "side_log_jungle_top_small",
    bottom: "side_log_jungle_top_small",
    left: "side_log_jungle_small",
    right: "side_log_jungle_small",
    shadow: "1",
  },
  {
    id: "kv31",
    front: "side_crafting_table_front_small",
    back: "side_crafting_table_front_small",
    top: "side_crafting_table_top_small",
    bottom: "side_planks_oak_small",
    left: "side_crafting_table_side_small",
    right: "side_crafting_table_side_small",
    shadow: "1",
  },
  {
    id: "ow91",
    front: "side_diamond_block_small",
    back: "side_diamond_block_small",
    top: "side_diamond_block_small",
    bottom: "side_diamond_block_small",
    left: "side_diamond_block_small",
    right: "side_diamond_block_small",
    shadow: "1",
  },
  {
    id: "ot83",
    front: "side_jukebox_side_small",
    back: "side_jukebox_side_small",
    top: "side_jukebox_top_small",
    bottom: "side_itemframe_background_small",
    left: "side_jukebox_side_small",
    right: "side_jukebox_side_small",
    shadow: "1",
  },
  {
    id: "z4m7",
    front: "side_tnt_side_small",
    back: "side_tnt_side_small",
    top: "side_tnt_top_small",
    bottom: "side_tnt_bottom_small",
    left: "side_tnt_side_small",
    right: "side_tnt_side_small",
    shadow: "1",
  },
  {
    id: "em59",
    front: "side_iron_block_small",
    back: "side_iron_block_small",
    top: "side_iron_block_small",
    bottom: "side_iron_block_small",
    left: "side_iron_block_small",
    right: "side_iron_block_small",
    shadow: "0",
  },
  {
    id: "dc25",
    front: "side_gold_block_small",
    back: "side_gold_block_small",
    top: "side_gold_block_small",
    bottom: "side_gold_block_small",
    left: "side_gold_block_small",
    right: "side_gold_block_small",
    shadow: "0",
  },
  {
    id: "co87",
    front: "side_lapis_block_small",
    back: "side_lapis_block_small",
    top: "side_lapis_block_small",
    bottom: "side_lapis_block_small",
    left: "side_lapis_block_small",
    right: "side_lapis_block_small",
    shadow: "0",
  },
  {
    id: "nr42",
    front: "side_emerald_block_small",
    back: "side_emerald_block_small",
    top: "side_emerald_block_small",
    bottom: "side_emerald_block_small",
    left: "side_emerald_block_small",
    right: "side_emerald_block_small",
    shadow: "0",
  },
  {
    id: "bd85",
    front: "side_redstone_block_small",
    back: "side_redstone_block_small",
    top: "side_redstone_block_small",
    bottom: "side_redstone_block_small",
    left: "side_redstone_block_small",
    right: "side_redstone_block_small",
    shadow: "0",
  },
  {
    id: "ot89",
    front: "side_slime_small",
    back: "side_slime_small",
    top: "side_slime_small",
    bottom: "side_slime_small",
    left: "side_slime_small",
    right: "side_slime_small",
    shadow: "0",
  },
  {
    id: "jl19",
    front: "side_hay_block_side_small",
    back: "side_hay_block_side_small",
    top: "side_hay_block_top_small",
    bottom: "side_hay_block_top_small",
    left: "side_hay_block_side_small",
    right: "side_hay_block_side_small",
    shadow: "1",
  },
  {
    id: "a7y6",
    front: "side_brick_small",
    back: "side_brick_small",
    top: "side_brick_small",
    bottom: "side_brick_small",
    left: "side_brick_small",
    right: "side_brick_small",
    shadow: "1",
  },
  {
    id: "cq42",
    front: "side_melon_side_small",
    back: "side_melon_side_small",
    top: "side_melon_top_small",
    bottom: "side_melon_top_small",
    left: "side_melon_side_small",
    right: "side_melon_side_small",
    shadow: "1",
  },
  {
    id: "vo99",
    front: "side_redstone_lamp_off_small",
    back: "side_redstone_lamp_off_small",
    top: "side_redstone_lamp_off_small",
    bottom: "side_redstone_lamp_off_small",
    left: "side_redstone_lamp_off_small",
    right: "side_redstone_lamp_off_small",
    shadow: "1",
  },
];

/** @description 羽翅 */
export const WING_COLOR = [
  { id: "d55c", color: "var(--white-75)" },
  { id: "di67", color: "rgba(231, 76, 60,0.75)" },
  { id: "oa91", color: "rgba(230, 126, 34,0.75)" },
  { id: "zf30", color: "rgba(241, 196, 15,0.75)" },
  { id: "fk07", color: "rgba(46, 204, 113,0.75)" },
  { id: "j0u8", color: "rgba(18, 203, 196,0.75)" },
  { id: "k79t", color: "rgba(52, 152, 219,0.75)" },
  { id: "it00", color: "rgba(190, 46, 221,0.75)" },
];
export const WING_IMG = [
  { id: "g30x", img: "wing_coral_fan_blue_small" },
  { id: "d5r4", img: "wing_coral_fan_pink_small" },
  { id: "g2z7", img: "wing_coral_fan_purple_small" },
  { id: "x6e7", img: "wing_coral_fan_red_small" },
  { id: "nd12", img: "wing_coral_fan_yellow_small" },
  { id: "h7q5", img: "wing_coral_plant_blue_small" },
  { id: "hv67", img: "wing_coral_plant_pink_small" },
  { id: "sa93", img: "wing_coral_plant_purple_small" },
  { id: "o8g3", img: "wing_coral_plant_red_small" },
  { id: "u54k", img: "wing_coral_plant_yellow_small" },
];

/** @description 部件键值信息列表 */
export const PART_KEY_INFO: YiBaoPartKeyInfo = {
  dd09: { type: "COLOR", name: "经典", price: "0" },
  ou51: { type: "COLOR", name: "红环", price: "100" },
  wr44: { type: "COLOR", name: "橙环", price: "100" },
  i4k2: { type: "COLOR", name: "黄环", price: "100" },
  yi92: { type: "COLOR", name: "绿环", price: "100" },
  x4k2: { type: "COLOR", name: "青环", price: "100" },
  d6h3: { type: "COLOR", name: "蓝环", price: "100" },
  dn92: { type: "COLOR", name: "紫环", price: "100" },
  tp44: { type: "IMG", name: "苹果", price: "100" },
  hq05: { type: "IMG", name: "竹子", price: "100" },
  e2n3: { type: "IMG", name: "烈焰粉", price: "100" },
  n9p2: { type: "IMG", name: "骨头", price: "100" },
  zo60: { type: "IMG", name: "岩浆桶", price: "100" },
  vc25: { type: "IMG", name: "水桶", price: "100" },
  qt21: { type: "IMG", name: "蛋糕", price: "100" },
  gz88: { type: "IMG", name: "胡萝卜", price: "100" },
  hs43: { type: "IMG", name: "熟鸡肉", price: "100" },
  zl95: { type: "IMG", name: "时钟", price: "100" },
  w52z: { type: "IMG", name: "煤炭", price: "100" },
  xt20: { type: "IMG", name: "指南针", price: "100" },
  uq54: { type: "IMG", name: "曲奇", price: "100" },
  la77: { type: "IMG", name: "钻石", price: "100" },
  lr11: { type: "IMG", name: "钻石镐", price: "100" },
  kk81: { type: "IMG", name: "钻石斧", price: "100" },
  e9k8: { type: "IMG", name: "钻石铲", price: "100" },
  b4n8: { type: "IMG", name: "钻石锄", price: "100" },
  og09: { type: "IMG", name: "钻石剑", price: "100" },
  jh83: { type: "IMG", name: "龙息", price: "100" },
  c3c7: { type: "IMG", name: "青金石", price: "100" },
  v4r8: { type: "IMG", name: "绿宝石", price: "100" },
  li63: { type: "IMG", name: "末影之眼", price: "100" },
  k1x0: { type: "IMG", name: "末影珍珠", price: "100" },
  mb84: { type: "IMG", name: "附魔之瓶", price: "100" },
  ra82: { type: "IMG", name: "火焰弹", price: "100" },
  t3g5: { type: "IMG", name: "焰火", price: "100" },
  cw30: { type: "IMG", name: "小丑鱼", price: "100" },
  fg95: { type: "IMG", name: "河豚", price: "100" },
  f7x7: { type: "IMG", name: "鲑鱼", price: "100" },
  k87g: { type: "IMG", name: "蒲公英", price: "100" },
  bb70: { type: "IMG", name: "玫瑰", price: "100" },
  tv90: { type: "IMG", name: "金锭", price: "100" },
  g9v9: { type: "IMG", name: "西瓜", price: "100" },
  ml06: { type: "IMG", name: "下界之星", price: "100" },
  jt50: { type: "IMG", name: "13", price: "100" },
  a5w0: { type: "IMG", name: "blocks", price: "100" },
  df69: { type: "IMG", name: "cat", price: "100" },
  l9g3: { type: "IMG", name: "chirp", price: "100" },
  w3a1: { type: "IMG", name: "far", price: "100" },
  mo53: { type: "IMG", name: "mellohi", price: "100" },
  ss35: { type: "IMG", name: "stal", price: "100" },
  qd12: { type: "IMG", name: "strad", price: "100" },
  iv15: { type: "IMG", name: "wait", price: "100" },
  w9j7: { type: "IMG", name: "ward", price: "100" },
  zp43: { type: "IMG", name: "红石粉", price: "100" },
  su32: { type: "IMG", name: "粘液球", price: "100" },
  g81a: { type: "IMG", name: "雪球", price: "100" },
  mb22: { type: "IMG", name: "不死图腾", price: "100" },
  o6o3: { type: "IMG", name: "三叉戟", price: "100" },
  sa20: { type: "COLOR", name: "经典", price: "0" },
  hq73: { type: "COLOR", name: "红线", price: "100" },
  wh10: { type: "COLOR", name: "橙线", price: "100" },
  qk29: { type: "COLOR", name: "黄线", price: "100" },
  x90w: { type: "COLOR", name: "绿线", price: "100" },
  wi00: { type: "COLOR", name: "青线", price: "100" },
  v4j2: { type: "COLOR", name: "蓝线", price: "100" },
  ev89: { type: "COLOR", name: "紫线", price: "100" },
  cx34: { type: "IMG", name: "泥土", price: "100" },
  v58o: { type: "IMG", name: "圆石", price: "100" },
  mq32: { type: "IMG", name: "下界岩", price: "100" },
  wl36: { type: "IMG", name: "灵魂沙", price: "100" },
  ts02: { type: "IMG", name: "基岩", price: "100" },
  tc30: { type: "IMG", name: "橡木", price: "100" },
  ad16: { type: "IMG", name: "云杉木", price: "100" },
  xb12: { type: "IMG", name: "深色橡木", price: "100" },
  ec53: { type: "IMG", name: "白桦木", price: "100" },
  jo73: { type: "IMG", name: "金合欢木", price: "100" },
  h0j8: { type: "IMG", name: "丛林木", price: "100" },
  ec25: { type: "IMG", name: "唱片机", price: "100" },
  sh59: { type: "IMG", name: "TNT", price: "100" },
  v7v4: { type: "IMG", name: "铁块", price: "100" },
  qc57: { type: "IMG", name: "金块", price: "100" },
  cu19: { type: "IMG", name: "青金石块", price: "100" },
  yf31: { type: "IMG", name: "绿宝石块", price: "100" },
  i04j: { type: "IMG", name: "红石块", price: "100" },
  b40h: { type: "IMG", name: "粘液块", price: "100" },
  c4l3: { type: "IMG", name: "干草块", price: "100" },
  vp00: { type: "IMG", name: "砖块", price: "100" },
  ic29: { type: "IMG", name: "西瓜", price: "100" },
  yd41: { type: "IMG", name: "红石灯", price: "100" },
  nu37: { type: "COLOR", name: "经典", price: "0" },
  b3r6: { type: "COLOR", name: "腮红", price: "100" },
  w7x1: { type: "COLOR", name: "腮橙", price: "100" },
  y5g2: { type: "COLOR", name: "腮黄", price: "100" },
  o00r: { type: "COLOR", name: "腮绿", price: "100" },
  e0d7: { type: "COLOR", name: "腮青", price: "100" },
  nr35: { type: "COLOR", name: "腮蓝", price: "100" },
  os17: { type: "COLOR", name: "腮紫", price: "100" },
  wt02: { type: "COLOR", name: "经典", price: "0" },
  tj88: { type: "COLOR", name: "赤瞳", price: "100" },
  lc39: { type: "COLOR", name: "橙瞳", price: "100" },
  lq72: { type: "COLOR", name: "黄瞳", price: "100" },
  b61b: { type: "COLOR", name: "绿瞳", price: "100" },
  ar02: { type: "COLOR", name: "青瞳", price: "100" },
  mc24: { type: "COLOR", name: "蓝瞳", price: "100" },
  bt67: { type: "COLOR", name: "紫瞳", price: "100" },
  ay75: { type: "COLOR", name: "经典", price: "0" },
  qs82: { type: "COLOR", name: "红嘴", price: "100" },
  v46e: { type: "COLOR", name: "橙嘴", price: "100" },
  t7y7: { type: "COLOR", name: "黄嘴", price: "100" },
  at06: { type: "COLOR", name: "绿嘴", price: "100" },
  rr93: { type: "COLOR", name: "青嘴", price: "100" },
  uu32: { type: "COLOR", name: "蓝嘴", price: "100" },
  v2i1: { type: "COLOR", name: "紫嘴", price: "100" },
  nw39: { type: "COLOR", name: "经典", price: "0" },
  et63: { type: "COLOR", name: "红面", price: "100" },
  ok10: { type: "COLOR", name: "橙面", price: "100" },
  ed38: { type: "COLOR", name: "黄面", price: "100" },
  mk09: { type: "COLOR", name: "绿面", price: "100" },
  kz18: { type: "COLOR", name: "青面", price: "100" },
  es19: { type: "COLOR", name: "蓝面", price: "100" },
  z31m: { type: "COLOR", name: "紫面", price: "100" },
  y8d9: { type: "IMG", name: "泥土", price: "100" },
  yw29: { type: "IMG", name: "草方块", price: "100" },
  a7f8: { type: "IMG", name: "圆石", price: "100" },
  uu92: { type: "IMG", name: "下界岩", price: "100" },
  w9p0: { type: "IMG", name: "灵魂沙", price: "100" },
  qk97: { type: "IMG", name: "基岩", price: "100" },
  vp82: { type: "IMG", name: "橡木", price: "100" },
  xs30: { type: "IMG", name: "云杉木", price: "100" },
  y93u: { type: "IMG", name: "深色橡木", price: "100" },
  zg30: { type: "IMG", name: "白桦木", price: "100" },
  gk79: { type: "IMG", name: "金合欢木", price: "100" },
  o4s2: { type: "IMG", name: "丛林木", price: "100" },
  kv31: { type: "IMG", name: "工作台", price: "100" },
  ow91: { type: "IMG", name: "钻石块", price: "100" },
  ot83: { type: "IMG", name: "唱片机", price: "100" },
  z4m7: { type: "IMG", name: "TNT", price: "100" },
  em59: { type: "IMG", name: "铁块", price: "100" },
  dc25: { type: "IMG", name: "金块", price: "100" },
  co87: { type: "IMG", name: "青金石块", price: "100" },
  nr42: { type: "IMG", name: "绿宝石块", price: "100" },
  bd85: { type: "IMG", name: "红石块", price: "100" },
  ot89: { type: "IMG", name: "粘液块", price: "100" },
  jl19: { type: "IMG", name: "干草块", price: "100" },
  a7y6: { type: "IMG", name: "砖块", price: "100" },
  cq42: { type: "IMG", name: "西瓜", price: "100" },
  vo99: { type: "IMG", name: "红石灯", price: "100" },
  d55c: { type: "COLOR", name: "经典", price: "0" },
  di67: { type: "COLOR", name: "红羽", price: "100" },
  oa91: { type: "COLOR", name: "橙羽", price: "100" },
  zf30: { type: "COLOR", name: "黄羽", price: "100" },
  fk07: { type: "COLOR", name: "绿羽", price: "100" },
  j0u8: { type: "COLOR", name: "青羽", price: "100" },
  k79t: { type: "COLOR", name: "蓝羽", price: "100" },
  it00: { type: "COLOR", name: "紫羽", price: "100" },
  g30x: { type: "IMG", name: "管珊瑚扇", price: "100" },
  d5r4: { type: "IMG", name: "脑纹珊瑚扇", price: "100" },
  g2z7: { type: "IMG", name: "气泡珊瑚扇", price: "100" },
  x6e7: { type: "IMG", name: "火珊瑚扇", price: "100" },
  nd12: { type: "IMG", name: "鹿角珊瑚扇", price: "100" },
  h7q5: { type: "IMG", name: "管珊瑚", price: "100" },
  hv67: { type: "IMG", name: "脑纹珊瑚", price: "100" },
  sa93: { type: "IMG", name: "气泡珊瑚", price: "100" },
  o8g3: { type: "IMG", name: "火珊瑚", price: "100" },
  u54k: { type: "IMG", name: "鹿角珊瑚", price: "100" },
};

/** 所有部件的键值对 */
export const PARTS_KEY_NAME: Record<Game.YiBao.PartType, string> = {
  annulus: "圆环",
  antenna: "天线",
  blush: "腮红",
  eye: "眼睛",
  mouth: "嘴巴",
  side: "六面",
  wing: "羽翅",
};

/** @description 所有部件键名 */
export const PART_KEY_LIST: Game.YiBao.PartType[] = [
  "annulus",
  "antenna",
  "blush",
  "eye",
  "mouth",
  "side",
  "wing",
];

/** 目前支持切换风格的部件 */
export const PART_SUPPORT_IMG = ["annulus", "antenna", "side", "wing"];
