// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddLink: typeof import('./src/components/business/Dialog/AddLink/index.vue')['default']
    ConfirmClose: typeof import('./src/components/business/Dialog/ConfirmClose/index.vue')['default']
    ConfirmNotice: typeof import('./src/components/business/Dialog/ConfirmNotice/index.vue')['default']
    FormImg: typeof import('./src/components/business/Form/FormImg/index.vue')['default']
    FormInput: typeof import('./src/components/business/Form/FormInput/index.vue')['default']
    FormRange: typeof import('./src/components/business/Form/FormRange/index.vue')['default']
    FormSelect: typeof import('./src/components/business/Form/FormSelect/index.vue')['default']
    GlobalSwitch: typeof import('./src/components/business/GlobalSwitch/index.vue')['default']
    KAttribute: typeof import('./src/components/business/Hero/K-Attribute/index.vue')['default']
    KButton: typeof import('./src/components/business/Parts/K-Button/index.vue')['default']
    KCheckbox: typeof import('./src/components/business/Parts/K-Checkbox/index.vue')['default']
    KDialog: typeof import('./src/components/business/Parts/K-Dialog/index.vue')['default']
    KHeroSort: typeof import('./src/components/business/Hero/K-HeroSort/index.vue')['default']
    KManageCard: typeof import('./src/components/business/Cards/K-ManageCard/index.vue')['default']
    KMessage: typeof import('./src/components/business/Parts/K-Message/index.vue')['default']
    KSkillTypeTag: typeof import('./src/components/business/Parts/K-SkillTypeTag/index.vue')['default']
    KTagSmall: typeof import('./src/components/business/Parts/K-TagSmall/index.vue')['default']
    LibBgVideo: typeof import('./src/components/common/LibBgVideo/index.vue')['default']
    LibCancelBtn: typeof import('./src/components/common/LibCancelBtn/index.vue')['default']
    LibCommitBtn: typeof import('./src/components/common/LibCommitBtn/index.vue')['default']
    LibDeleteBtn: typeof import('./src/components/common/LibDeleteBtn/index.vue')['default']
    LibFlipBox: typeof import('./src/components/common/LibFlipBox/index.vue')['default']
    LibGridLayout: typeof import('./src/components/common/LibGridLayout/index.vue')['default']
    LibIcon: typeof import('./src/components/common/LibIcon/index.vue')['default']
    LibLoading: typeof import('./src/components/common/LibLoading/index.vue')['default']
    LibMask: typeof import('./src/components/common/LibMask/index.vue')['default']
    LibMaskClose: typeof import('./src/components/common/LibMaskClose/index.vue')['default']
    LibRange: typeof import('./src/components/common/LibRange/index.vue')['default']
    LibRichText: typeof import('./src/components/common/LibRichText/index.vue')['default']
    LibStripeBtn: typeof import('./src/components/common/LibStripeBtn/index.vue')['default']
    LibSvg: typeof import('./src/components/common/LibSvg/index.vue')['default']
    LibUpdateBtn: typeof import('./src/components/common/LibUpdateBtn/index.vue')['default']
    Link: typeof import('./src/components/business/Sidebar/SidebarItem/Link.vue')['default']
    PlayVoice: typeof import('./src/components/business/Tool/PlayVoice/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectHero: typeof import('./src/components/business/Tool/SelectHero/index.vue')['default']
    SelectImg: typeof import('./src/components/business/Tool/SelectImg/index.vue')['default']
    Sidebar: typeof import('./src/components/business/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/components/business/Sidebar/SidebarItem/index.vue')['default']
  }
}
