export * from "./modules/scene-tip";
export * from "./modules/route-path";
export * from "./modules/resource-name";
export * from "./modules/mouse-tip";
export * from "./modules/message-tip";
export * from "./modules/local-key";
export * from "./modules/help-tip";
export * from "./modules/confirm-tip";
export * from "./modules/base";
export * as YIBAO_PART from "./modules/yibao-part";
export * as MARKER_CONFIG from "./modules/marker-config";
export * as GAME_PROP from "./modules/game-prop";
export * as GAME_CONFIG from "./modules/game-config";
export * as GAME_CHANCE from "./modules/game-chance";
export * as DEFAULT from "./modules/default";
