// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    403: typeof import('./../components/ErrorMessage/403.vue')['default']
    404: typeof import('./../components/ErrorMessage/404.vue')['default']
    500: typeof import('./../components/ErrorMessage/500.vue')['default']
    AddLink: typeof import('./../components/business/Dialog/AddLink/index.vue')['default']
    ConfirmClose: typeof import('./../components/business/Dialog/ConfirmClose/index.vue')['default']
    'ConfirmNotice(待使用)': typeof import('./../components/business/Dialog/ConfirmNotice(待使用)/index.vue')['default']
    FormImg: typeof import('./../components/business/Form/FormImg/index.vue')['default']
    FormInput: typeof import('./../components/business/Form/FormInput/index.vue')['default']
    FormRange: typeof import('./../components/business/Form/FormRange/index.vue')['default']
    FormSelect: typeof import('./../components/business/Form/FormSelect/index.vue')['default']
    GlobalSwitch: typeof import('./../components/business/GlobalSwitch/index.vue')['default']
    KButton: typeof import('./../components/business/Parts/K-Button/index.vue')['default']
    KCheckbox: typeof import('./../components/business/Parts/K-Checkbox/index.vue')['default']
    'KDialog(template)': typeof import('./../components/business/Parts/K-Dialog(template)/index.vue')['default']
    KManageCard: typeof import('./../components/business/Cards/K-ManageCard/index.vue')['default']
    KMessage: typeof import('./../components/business/Parts/K-Message/index.vue')['default']
    KSkillTypeTag: typeof import('./../components/business/Parts/K-SkillTypeTag/index.vue')['default']
    LibBgVideo: typeof import('./../components/common/LibBgVideo/index.vue')['default']
    LibCancelBtn: typeof import('./../components/common/LibCancelBtn/index.vue')['default']
    LibCommitBtn: typeof import('./../components/common/LibCommitBtn/index.vue')['default']
    LibDeleteBtn: typeof import('./../components/common/LibDeleteBtn/index.vue')['default']
    LibFlipBox: typeof import('./../components/common/LibFlipBox/index.vue')['default']
    LibGridLayout: typeof import('./../components/common/LibGridLayout/index.vue')['default']
    LibIcon: typeof import('./../components/common/LibIcon/index.vue')['default']
    LibLoading: typeof import('./../components/common/LibLoading/index.vue')['default']
    LibMask: typeof import('./../components/common/LibMask/index.vue')['default']
    LibMaskClose: typeof import('./../components/common/LibMaskClose/index.vue')['default']
    LibRange: typeof import('./../components/common/LibRange/index.vue')['default']
    LibRichText: typeof import('./../components/common/LibRichText/index.vue')['default']
    LibStripeBtn: typeof import('./../components/common/LibStripeBtn/index.vue')['default']
    LibSvg: typeof import('./../components/common/LibSvg/index.vue')['default']
    LibUpdateBtn: typeof import('./../components/common/LibUpdateBtn/index.vue')['default']
    PlayVoice: typeof import('./../components/business/Tool/PlayVoice/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectHero: typeof import('./../components/business/Tool/SelectHero/index.vue')['default']
    SelectImg: typeof import('./../components/business/Tool/SelectImg/index.vue')['default']
  }
}
